import { chromium } from "@playwright/test";
const base = "http://localhost:3100";
const browser = await chromium.launch({ args: ["--no-sandbox"] });
const ctx = await browser.newContext({ viewport: { width: 1194, height: 834 }, hasTouch: true });
const page = await ctx.newPage();
await page.goto(base + "/login");
await page.getByPlaceholder("vous@restaurant.pf").fill("manager@manaresto.pf");
await page.getByLabel("Mot de passe").fill("demo1234");
await page.getByRole("button", { name: "Se connecter" }).click();
await page.waitForURL(/\/(pos|admin)/);
const out = process.argv[2];
const shot = async (name) => { await page.waitForTimeout(700); await page.screenshot({ path: `${out}/${name}.png` }); };
await page.goto(base + "/pos"); await shot("01-plan-de-salle");
const occupied = page.locator("button[title='Plats envoyés'], button[title='Commande en cours']").first();
await occupied.click(); await page.waitForURL(/\/pos\/order\//); await shot("02-commande");
await page.getByRole("button", { name: "Plats", exact: true }).click();
await page.getByRole("button", { name: /^Burger Bacon/ }).click(); await shot("03-options-produit");
await page.keyboard.press("Escape");
await page.getByRole("button", { name: /Payer/ }).click(); await shot("04-paiement");
await page.getByRole("button", { name: /Diviser l'addition/ }).click(); await shot("05-diviser-addition");
await page.keyboard.press("Escape");
await page.evaluate(() => document.documentElement.setAttribute("data-theme", "dark"));
await shot("06-commande-mode-sombre");
await page.evaluate(() => document.documentElement.setAttribute("data-theme", "light"));
await page.goto(base + "/pos/cash"); await shot("07-caisse");
await page.goto(base + "/admin"); await page.waitForSelector("text=CA par heure"); await shot("08-tableau-de-bord");
await page.goto(base + "/admin/catalog/products"); await page.waitForSelector("text=Burger Bacon"); await shot("09-catalogue");
await page.goto(base + "/admin/floor"); await page.waitForSelector("text=T01"); await shot("10-editeur-salle");
await page.goto(base + "/admin/users"); await page.waitForSelector("text=Propriétaire"); await shot("11-utilisateurs");
await page.goto(base + "/pos/login"); await shot("12-connexion-pin");
await browser.close();
